// <auto-generated />
using System;
using Beer2beer.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Beer2beer.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240217232058_UpdateArticle")]
    partial class UpdateArticle
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("Beer2beer.Core.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Balance")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EntryDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 8,
                            Balance = 5956.443059489824384m,
                            Email = "Alanis.Ziemann99@hotmail.com",
                            FullName = "Prudence Lakin"
                        },
                        new
                        {
                            Id = 79,
                            Balance = 5084.064957297107143m,
                            Email = "Ferne.Shields48@yahoo.com",
                            FullName = "Wayne Gusikowski"
                        },
                        new
                        {
                            Id = 78,
                            Email = "Flavie.Schulist71@yahoo.com",
                            FullName = "Eunice Roberts"
                        },
                        new
                        {
                            Id = 11,
                            Email = "Elva71@yahoo.com",
                            FullName = "Domenica Mertz"
                        },
                        new
                        {
                            Id = 2,
                            Email = "Skyla.Wintheiser6@yahoo.com",
                            FullName = "Gideon Considine"
                        },
                        new
                        {
                            Id = 98,
                            Balance = 3586.662947343290176m,
                            Email = "Cletus_Kuhlman@gmail.com",
                            FullName = "Rafael Larkin"
                        },
                        new
                        {
                            Id = 41,
                            Email = "Antonia93@yahoo.com",
                            FullName = "Kaycee Tremblay"
                        },
                        new
                        {
                            Id = 27,
                            Email = "Wilfred.Satterfield@yahoo.com",
                            FullName = "Ronny Harber"
                        },
                        new
                        {
                            Id = 82,
                            Balance = 5040.978198794948035m,
                            Email = "Jamal53@gmail.com",
                            FullName = "Aletha Mraz"
                        },
                        new
                        {
                            Id = 69,
                            Balance = 5694.139550750585725m,
                            Email = "Gerson25@hotmail.com",
                            FullName = "Oswald McClure"
                        },
                        new
                        {
                            Id = 57,
                            Email = "Houston_Torphy@hotmail.com",
                            FullName = "Lemuel Jakubowski"
                        },
                        new
                        {
                            Id = 56,
                            Email = "Linnea54@hotmail.com",
                            FullName = "Carmine Weissnat"
                        },
                        new
                        {
                            Id = 94,
                            Email = "Vince20@yahoo.com",
                            FullName = "Santa Cremin"
                        },
                        new
                        {
                            Id = 99,
                            Email = "Birdie42@gmail.com",
                            FullName = "Frederic Wisozk"
                        },
                        new
                        {
                            Id = 3,
                            Balance = 9286.975337531326588m,
                            Email = "Wava.Schuppe@yahoo.com",
                            FullName = "Arch Murazik"
                        },
                        new
                        {
                            Id = 93,
                            Balance = 6617.25988350263398m,
                            Email = "Lavern_Ortiz52@yahoo.com",
                            FullName = "Donavon Stanton"
                        },
                        new
                        {
                            Id = 1,
                            Balance = 8216.488309988251765m,
                            Email = "Zion_Lindgren55@gmail.com",
                            FullName = "Kale Bode"
                        },
                        new
                        {
                            Id = 92,
                            Email = "Juvenal.DuBuque@yahoo.com",
                            FullName = "Elisabeth Ortiz"
                        },
                        new
                        {
                            Id = 21,
                            Balance = 6288.431971537208503m,
                            Email = "Earnest66@gmail.com",
                            FullName = "Manuel Lockman"
                        },
                        new
                        {
                            Id = 59,
                            Email = "Nia64@gmail.com",
                            FullName = "Helen Shields"
                        },
                        new
                        {
                            Id = 52,
                            Balance = 6454.050170685516046m,
                            Email = "Javon.Schaden@hotmail.com",
                            FullName = "Shania Marvin"
                        },
                        new
                        {
                            Id = 46,
                            Balance = 2400.623756532119359m,
                            Email = "Ally90@yahoo.com",
                            FullName = "Louvenia Renner"
                        },
                        new
                        {
                            Id = 70,
                            Balance = 2076.994230189512545m,
                            Email = "Dorian87@hotmail.com",
                            FullName = "Brain Gleichner"
                        },
                        new
                        {
                            Id = 64,
                            Balance = 1754.24825476278775m,
                            Email = "Lavada_Brekke@hotmail.com",
                            FullName = "Kaia Bergstrom"
                        },
                        new
                        {
                            Id = 39,
                            Balance = 1106.999125053777262m,
                            Email = "Dandre_Reilly@gmail.com",
                            FullName = "Fay Prosacco"
                        },
                        new
                        {
                            Id = 76,
                            Balance = 8629.346863160026156m,
                            Email = "Cory_Anderson17@yahoo.com",
                            FullName = "Felipe Nitzsche"
                        },
                        new
                        {
                            Id = 42,
                            Email = "Cindy78@yahoo.com",
                            FullName = "Jennifer Renner"
                        },
                        new
                        {
                            Id = 60,
                            Email = "Ima.McCullough16@gmail.com",
                            FullName = "Stephon Trantow"
                        },
                        new
                        {
                            Id = 37,
                            Balance = 5865.980252706111295m,
                            Email = "Kenyon.OHara@yahoo.com",
                            FullName = "Britney Terry"
                        },
                        new
                        {
                            Id = 44,
                            Email = "Violet.Gleason@gmail.com",
                            FullName = "Alanna Feeney"
                        },
                        new
                        {
                            Id = 50,
                            Balance = 7165.91762472208591m,
                            Email = "Sophia.Spencer@yahoo.com",
                            FullName = "Amy D'Amore"
                        },
                        new
                        {
                            Id = 85,
                            Balance = 4735.009597073422204m,
                            Email = "Janis79@gmail.com",
                            FullName = "Madeline Hauck"
                        },
                        new
                        {
                            Id = 91,
                            Email = "Nikko38@hotmail.com",
                            FullName = "Christine Kiehn"
                        },
                        new
                        {
                            Id = 26,
                            Email = "Newton.Johnson96@gmail.com",
                            FullName = "Conner Schinner"
                        },
                        new
                        {
                            Id = 81,
                            Balance = 9508.603635241670926m,
                            Email = "Kiarra_Hahn95@yahoo.com",
                            FullName = "Kathleen Nitzsche"
                        },
                        new
                        {
                            Id = 23,
                            Email = "Emanuel_Dietrich@hotmail.com",
                            FullName = "Edgardo Rau"
                        },
                        new
                        {
                            Id = 10,
                            Email = "Quentin_Jast47@gmail.com",
                            FullName = "Evalyn Williamson"
                        },
                        new
                        {
                            Id = 96,
                            Balance = 8029.804531340930986m,
                            Email = "Vance.Stokes21@hotmail.com",
                            FullName = "Magdalena Zulauf"
                        },
                        new
                        {
                            Id = 35,
                            Email = "Suzanne.Hirthe@yahoo.com",
                            FullName = "Antwan Balistreri"
                        },
                        new
                        {
                            Id = 65,
                            Balance = 6402.511651937337595m,
                            Email = "Sunny60@hotmail.com",
                            FullName = "Major Frami"
                        },
                        new
                        {
                            Id = 18,
                            Balance = 711.3496528752575248m,
                            Email = "Lexi_Reynolds27@hotmail.com",
                            FullName = "Constance Walker"
                        },
                        new
                        {
                            Id = 28,
                            Email = "Thora.Block@hotmail.com",
                            FullName = "Ramon Wunsch"
                        },
                        new
                        {
                            Id = 83,
                            Balance = 5862.840550098312241m,
                            Email = "Aurelie92@gmail.com",
                            FullName = "Gloria Strosin"
                        },
                        new
                        {
                            Id = 88,
                            Balance = 8730.434213944253128m,
                            Email = "Bernice.Gutmann@yahoo.com",
                            FullName = "Chance Watsica"
                        },
                        new
                        {
                            Id = 53,
                            Email = "Jessyca79@yahoo.com",
                            FullName = "Halie Klein"
                        },
                        new
                        {
                            Id = 86,
                            Balance = 7433.704899717555799m,
                            Email = "Clarabelle_Jacobs@yahoo.com",
                            FullName = "Valerie Doyle"
                        },
                        new
                        {
                            Id = 100,
                            Balance = 7599.492525649930498m,
                            Email = "Astrid_Grant@hotmail.com",
                            FullName = "Elisabeth McClure"
                        },
                        new
                        {
                            Id = 80,
                            Balance = 7637.348071715350636m,
                            Email = "Zion.Toy54@hotmail.com",
                            FullName = "Wilmer Conn"
                        },
                        new
                        {
                            Id = 66,
                            Balance = 4388.383120600450927m,
                            Email = "Mac48@hotmail.com",
                            FullName = "Noelia Windler"
                        },
                        new
                        {
                            Id = 72,
                            Email = "Domenico.Ullrich@yahoo.com",
                            FullName = "Clyde Adams"
                        },
                        new
                        {
                            Id = 74,
                            Balance = 9047.30955512954428m,
                            Email = "Vaughn_Klein77@yahoo.com",
                            FullName = "Hazel Gerlach"
                        },
                        new
                        {
                            Id = 25,
                            Balance = 8461.061112547553212m,
                            Email = "Maryse87@yahoo.com",
                            FullName = "Reanna Bauch"
                        },
                        new
                        {
                            Id = 9,
                            Email = "Lou_Hahn@yahoo.com",
                            FullName = "Mckenna Wisoky"
                        },
                        new
                        {
                            Id = 48,
                            Email = "Salvatore_Hane@gmail.com",
                            FullName = "Liza Rogahn"
                        },
                        new
                        {
                            Id = 16,
                            Balance = 6050.851616761897186m,
                            Email = "Shanelle_Torp80@gmail.com",
                            FullName = "Aglae Grady"
                        },
                        new
                        {
                            Id = 5,
                            Balance = 223.5655392800660128m,
                            Email = "Keegan39@gmail.com",
                            FullName = "Damien Hauck"
                        },
                        new
                        {
                            Id = 43,
                            Email = "Shannon3@yahoo.com",
                            FullName = "Breanne Kertzmann"
                        },
                        new
                        {
                            Id = 32,
                            Balance = 8091.416740943127052m,
                            Email = "Manuel.Kulas@yahoo.com",
                            FullName = "Isaias Kassulke"
                        },
                        new
                        {
                            Id = 87,
                            Balance = 3815.76592020910474m,
                            Email = "Adella77@gmail.com",
                            FullName = "Rosetta Haag"
                        },
                        new
                        {
                            Id = 55,
                            Email = "Adalberto_Hansen@gmail.com",
                            FullName = "Narciso Collier"
                        },
                        new
                        {
                            Id = 45,
                            Balance = 5013.565116149850787m,
                            Email = "Emely77@gmail.com",
                            FullName = "Allen Lakin"
                        },
                        new
                        {
                            Id = 68,
                            Balance = 509.0729838836316742m,
                            Email = "Alfonzo_Jerde85@hotmail.com",
                            FullName = "Dereck Kassulke"
                        },
                        new
                        {
                            Id = 14,
                            Balance = 5758.309886644838764m,
                            Email = "Sister_Jones@gmail.com",
                            FullName = "Rodrigo Stanton"
                        },
                        new
                        {
                            Id = 38,
                            Balance = 2283.410223009344197m,
                            Email = "Isom_Abshire@yahoo.com",
                            FullName = "Lavada Mitchell"
                        },
                        new
                        {
                            Id = 47,
                            Email = "Jolie.Jerde@hotmail.com",
                            FullName = "Glenna Considine"
                        },
                        new
                        {
                            Id = 17,
                            Balance = 781.8893311437293482m,
                            Email = "Halle_Ernser85@yahoo.com",
                            FullName = "Lamar Kohler"
                        },
                        new
                        {
                            Id = 19,
                            Balance = 4480.049757887954128m,
                            Email = "Vincenzo.Kozey38@hotmail.com",
                            FullName = "Aileen Aufderhar"
                        },
                        new
                        {
                            Id = 29,
                            Email = "Faye.Turcotte38@yahoo.com",
                            FullName = "Annabelle Schuster"
                        },
                        new
                        {
                            Id = 7,
                            Email = "Marianna11@gmail.com",
                            FullName = "Scot Bashirian"
                        },
                        new
                        {
                            Id = 24,
                            Balance = 3351.699251588867563m,
                            Email = "Deangelo95@hotmail.com",
                            FullName = "Alfonso Willms"
                        },
                        new
                        {
                            Id = 13,
                            Balance = 2083.333708105309846m,
                            Email = "Amani.Herman@hotmail.com",
                            FullName = "Hettie Conn"
                        },
                        new
                        {
                            Id = 54,
                            Email = "Preston_Kris54@yahoo.com",
                            FullName = "Cletus Kub"
                        },
                        new
                        {
                            Id = 67,
                            Balance = 1900.853358331703203m,
                            Email = "Lyric.Champlin@yahoo.com",
                            FullName = "Donnie Bergstrom"
                        },
                        new
                        {
                            Id = 15,
                            Email = "Harvey_Sporer@gmail.com",
                            FullName = "Melba Prosacco"
                        },
                        new
                        {
                            Id = 31,
                            Email = "Helene_Hayes@gmail.com",
                            FullName = "Amira Marks"
                        },
                        new
                        {
                            Id = 58,
                            Email = "Jazlyn.Kunde@hotmail.com",
                            FullName = "Wilhelm Romaguera"
                        },
                        new
                        {
                            Id = 63,
                            Balance = 8792.468059277129347m,
                            Email = "Kylee92@gmail.com",
                            FullName = "Henri Reilly"
                        },
                        new
                        {
                            Id = 90,
                            Balance = 8329.520759736819367m,
                            Email = "Delilah_Becker38@gmail.com",
                            FullName = "Elenora Blanda"
                        },
                        new
                        {
                            Id = 61,
                            Balance = 8079.264806140888777m,
                            Email = "Alessandra18@yahoo.com",
                            FullName = "Godfrey Anderson"
                        },
                        new
                        {
                            Id = 84,
                            Email = "Reece_Schimmel@yahoo.com",
                            FullName = "Randal Kreiger"
                        },
                        new
                        {
                            Id = 77,
                            Balance = 6007.961265966423136m,
                            Email = "Crystal_Hane@yahoo.com",
                            FullName = "Pearlie Jones"
                        },
                        new
                        {
                            Id = 51,
                            Balance = 3169.962646833600892m,
                            Email = "Janie18@hotmail.com",
                            FullName = "Kassandra Beatty"
                        },
                        new
                        {
                            Id = 71,
                            Email = "Immanuel36@hotmail.com",
                            FullName = "Elsa Simonis"
                        },
                        new
                        {
                            Id = 36,
                            Balance = 1464.533740626296284m,
                            Email = "Tamia_Emard@hotmail.com",
                            FullName = "Della Moore"
                        },
                        new
                        {
                            Id = 20,
                            Email = "Jon_Parker@gmail.com",
                            FullName = "Rossie Feil"
                        },
                        new
                        {
                            Id = 89,
                            Email = "Lance_Cartwright54@gmail.com",
                            FullName = "Margaretta Kilback"
                        },
                        new
                        {
                            Id = 34,
                            Balance = 1557.785868890165353m,
                            Email = "Alda_Ankunding71@hotmail.com",
                            FullName = "Ernesto Abshire"
                        },
                        new
                        {
                            Id = 33,
                            Email = "Allan.Stiedemann46@yahoo.com",
                            FullName = "Anika Rath"
                        },
                        new
                        {
                            Id = 49,
                            Email = "Helmer8@gmail.com",
                            FullName = "Gus Bernier"
                        },
                        new
                        {
                            Id = 95,
                            Email = "Gunnar88@hotmail.com",
                            FullName = "Brando Erdman"
                        },
                        new
                        {
                            Id = 40,
                            Email = "Gerald.Tremblay@yahoo.com",
                            FullName = "Joshuah Nolan"
                        },
                        new
                        {
                            Id = 73,
                            Email = "Deontae_Boehm90@hotmail.com",
                            FullName = "Janice Pollich"
                        },
                        new
                        {
                            Id = 30,
                            Email = "Gus.Medhurst39@yahoo.com",
                            FullName = "Joannie Dooley"
                        },
                        new
                        {
                            Id = 4,
                            Balance = 8550.385031199509497m,
                            Email = "Kevin75@gmail.com",
                            FullName = "Drew Stracke"
                        },
                        new
                        {
                            Id = 75,
                            Email = "Julien98@gmail.com",
                            FullName = "Isidro O'Hara"
                        },
                        new
                        {
                            Id = 22,
                            Balance = 3017.604824600854762m,
                            Email = "Jalon.Christiansen@hotmail.com",
                            FullName = "Jackeline Koch"
                        },
                        new
                        {
                            Id = 12,
                            Balance = 9987.082220429387776m,
                            Email = "Norene14@hotmail.com",
                            FullName = "Blanca Terry"
                        },
                        new
                        {
                            Id = 6,
                            Balance = 9955.611709677949501m,
                            Email = "Dorothea.Treutel@hotmail.com",
                            FullName = "Lexi Torphy"
                        },
                        new
                        {
                            Id = 62,
                            Email = "Joel_Rosenbaum@hotmail.com",
                            FullName = "Junius Osinski"
                        },
                        new
                        {
                            Id = 97,
                            Email = "Jeffrey.Carter87@yahoo.com",
                            FullName = "Maximilian Schinner"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
