// <auto-generated />
using System;
using Beer2beer.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Beer2beer.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240217222653_SupplierPoco")]
    partial class SupplierPoco
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("Beer2beer.Core.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Balance")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EntryDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 43,
                            Email = "Landen.Dare69@gmail.com",
                            FullName = "Kelley Mann"
                        },
                        new
                        {
                            Id = 17,
                            Email = "Antwon_Beahan@yahoo.com",
                            FullName = "Roel Dickens"
                        },
                        new
                        {
                            Id = 10,
                            Email = "Lela_Schimmel64@hotmail.com",
                            FullName = "Muhammad Cremin"
                        },
                        new
                        {
                            Id = 67,
                            Email = "Elouise_Grimes86@hotmail.com",
                            FullName = "Kali Nolan"
                        },
                        new
                        {
                            Id = 47,
                            Email = "Antonietta43@hotmail.com",
                            FullName = "Anahi Morar"
                        },
                        new
                        {
                            Id = 33,
                            Email = "Webster61@hotmail.com",
                            FullName = "Brandt Greenfelder"
                        },
                        new
                        {
                            Id = 6,
                            Email = "Hollie_Effertz@gmail.com",
                            FullName = "Vanessa Smitham"
                        },
                        new
                        {
                            Id = 50,
                            Balance = 4647.529549787958712m,
                            Email = "Jack80@hotmail.com",
                            FullName = "Shanna Bartell"
                        },
                        new
                        {
                            Id = 62,
                            Email = "Gilda_Koepp@yahoo.com",
                            FullName = "Elda Homenick"
                        },
                        new
                        {
                            Id = 85,
                            Email = "Jennifer66@hotmail.com",
                            FullName = "Reynold Renner"
                        },
                        new
                        {
                            Id = 100,
                            Balance = 2520.712533468357865m,
                            Email = "Clarabelle27@gmail.com",
                            FullName = "Watson Rempel"
                        },
                        new
                        {
                            Id = 76,
                            Email = "Elias68@gmail.com",
                            FullName = "Alf Kautzer"
                        },
                        new
                        {
                            Id = 45,
                            Balance = 6538.29819246463366m,
                            Email = "Braden.Windler0@hotmail.com",
                            FullName = "Orland Hauck"
                        },
                        new
                        {
                            Id = 60,
                            Balance = 4897.324950392734408m,
                            Email = "Noble.Jacobson94@yahoo.com",
                            FullName = "Lafayette Johnson"
                        },
                        new
                        {
                            Id = 94,
                            Balance = 2495.561784508726471m,
                            Email = "Ashtyn82@gmail.com",
                            FullName = "Terry Ledner"
                        },
                        new
                        {
                            Id = 32,
                            Balance = 8741.006395312243942m,
                            Email = "Norval1@yahoo.com",
                            FullName = "Cora Ritchie"
                        },
                        new
                        {
                            Id = 23,
                            Email = "Lane.Carroll@hotmail.com",
                            FullName = "Dayna Bartell"
                        },
                        new
                        {
                            Id = 29,
                            Balance = 6287.067608893757839m,
                            Email = "Vivien89@gmail.com",
                            FullName = "Annamarie Swift"
                        },
                        new
                        {
                            Id = 42,
                            Email = "Curt.Jerde7@hotmail.com",
                            FullName = "Fay Beatty"
                        },
                        new
                        {
                            Id = 18,
                            Balance = 9459.810873887932711m,
                            Email = "Larissa22@hotmail.com",
                            FullName = "Kade Roob"
                        },
                        new
                        {
                            Id = 68,
                            Email = "Leonie_Hauck19@gmail.com",
                            FullName = "Sandy Ullrich"
                        },
                        new
                        {
                            Id = 22,
                            Balance = 6361.470603743938462m,
                            Email = "Ulises.Schmitt48@gmail.com",
                            FullName = "Ollie Bashirian"
                        },
                        new
                        {
                            Id = 59,
                            Email = "Selena_Schumm75@gmail.com",
                            FullName = "Kaia Kovacek"
                        },
                        new
                        {
                            Id = 69,
                            Balance = 916.7568498887807746m,
                            Email = "Katrine.Okuneva5@yahoo.com",
                            FullName = "Ibrahim Bartoletti"
                        },
                        new
                        {
                            Id = 8,
                            Balance = 8349.179369242743019m,
                            Email = "Alec.Jacobson8@yahoo.com",
                            FullName = "Melba Paucek"
                        },
                        new
                        {
                            Id = 87,
                            Balance = 9855.405678298118014m,
                            Email = "Carmelo.Howell@gmail.com",
                            FullName = "Rico Sipes"
                        },
                        new
                        {
                            Id = 55,
                            Email = "Stuart28@yahoo.com",
                            FullName = "Patsy Farrell"
                        },
                        new
                        {
                            Id = 72,
                            Email = "Jaiden_Rau24@hotmail.com",
                            FullName = "Sandy Kuvalis"
                        },
                        new
                        {
                            Id = 27,
                            Balance = 2394.303681643985242m,
                            Email = "Lacey.Mitchell@hotmail.com",
                            FullName = "Kellen Christiansen"
                        },
                        new
                        {
                            Id = 66,
                            Email = "Delbert31@gmail.com",
                            FullName = "Haley Prosacco"
                        },
                        new
                        {
                            Id = 84,
                            Balance = 9035.059944356489944m,
                            Email = "Jamar83@hotmail.com",
                            FullName = "Moshe Sanford"
                        },
                        new
                        {
                            Id = 5,
                            Email = "Hiram82@yahoo.com",
                            FullName = "Lawson Hoeger"
                        },
                        new
                        {
                            Id = 11,
                            Email = "Lisa.Nolan19@gmail.com",
                            FullName = "Alysson Lowe"
                        },
                        new
                        {
                            Id = 49,
                            Email = "Ezekiel6@yahoo.com",
                            FullName = "Jovan Flatley"
                        },
                        new
                        {
                            Id = 30,
                            Email = "Jovan_Smith@hotmail.com",
                            FullName = "Reyna Gorczany"
                        },
                        new
                        {
                            Id = 44,
                            Balance = 5481.170055372651463m,
                            Email = "Kody.Hilpert14@yahoo.com",
                            FullName = "Ramona Lueilwitz"
                        },
                        new
                        {
                            Id = 35,
                            Email = "Jordi94@gmail.com",
                            FullName = "Hailie Toy"
                        },
                        new
                        {
                            Id = 96,
                            Balance = 469.4673866090257171m,
                            Email = "Delpha_Legros@gmail.com",
                            FullName = "Lilla Schamberger"
                        },
                        new
                        {
                            Id = 56,
                            Email = "Rhoda25@yahoo.com",
                            FullName = "Ariel Zieme"
                        },
                        new
                        {
                            Id = 7,
                            Email = "Adrien.Pollich43@hotmail.com",
                            FullName = "Rae Jacobs"
                        },
                        new
                        {
                            Id = 19,
                            Balance = 9464.021264470196368m,
                            Email = "Gunner.Baumbach64@gmail.com",
                            FullName = "Dave Upton"
                        },
                        new
                        {
                            Id = 65,
                            Email = "Hanna84@gmail.com",
                            FullName = "Frederik Bernhard"
                        },
                        new
                        {
                            Id = 53,
                            Email = "Moises_Terry@yahoo.com",
                            FullName = "Maida Flatley"
                        },
                        new
                        {
                            Id = 46,
                            Balance = 5544.766688518966897m,
                            Email = "Miracle22@yahoo.com",
                            FullName = "Marcella Wyman"
                        },
                        new
                        {
                            Id = 57,
                            Balance = 974.6844562393407217m,
                            Email = "Caleb13@yahoo.com",
                            FullName = "Misael Hoeger"
                        },
                        new
                        {
                            Id = 48,
                            Email = "Geovany.Gaylord@hotmail.com",
                            FullName = "Izabella Strosin"
                        },
                        new
                        {
                            Id = 13,
                            Email = "Sonny39@yahoo.com",
                            FullName = "Pedro Hackett"
                        },
                        new
                        {
                            Id = 86,
                            Email = "Fredy_Dietrich@hotmail.com",
                            FullName = "Kenneth Mann"
                        },
                        new
                        {
                            Id = 25,
                            Email = "Alayna.Kris@gmail.com",
                            FullName = "Shemar Hettinger"
                        },
                        new
                        {
                            Id = 99,
                            Balance = 7826.727279945866104m,
                            Email = "Arlo.Heathcote66@hotmail.com",
                            FullName = "Katrine Hayes"
                        },
                        new
                        {
                            Id = 89,
                            Email = "Gust.Brakus@yahoo.com",
                            FullName = "Dedric Lakin"
                        },
                        new
                        {
                            Id = 58,
                            Balance = 7775.403288950926837m,
                            Email = "Bell2@hotmail.com",
                            FullName = "Seth Hermiston"
                        },
                        new
                        {
                            Id = 64,
                            Balance = 2206.456342970023891m,
                            Email = "Garry.Jenkins90@gmail.com",
                            FullName = "Mabel Buckridge"
                        },
                        new
                        {
                            Id = 36,
                            Balance = 5079.452222995789231m,
                            Email = "Alfreda.Rosenbaum17@gmail.com",
                            FullName = "Laurie Funk"
                        },
                        new
                        {
                            Id = 3,
                            Balance = 7538.085442928364895m,
                            Email = "Elody.Robel26@hotmail.com",
                            FullName = "Nayeli Ritchie"
                        },
                        new
                        {
                            Id = 37,
                            Balance = 1470.196449193876777m,
                            Email = "Kaylin96@gmail.com",
                            FullName = "Fay Kohler"
                        },
                        new
                        {
                            Id = 4,
                            Email = "Immanuel_Runolfsson48@hotmail.com",
                            FullName = "Tianna Borer"
                        },
                        new
                        {
                            Id = 91,
                            Email = "Emmie.Satterfield@yahoo.com",
                            FullName = "Louisa Hickle"
                        },
                        new
                        {
                            Id = 41,
                            Balance = 2468.436940233569557m,
                            Email = "Maia.Nader8@hotmail.com",
                            FullName = "Oswald Mante"
                        },
                        new
                        {
                            Id = 75,
                            Email = "Mitchel_Ullrich@yahoo.com",
                            FullName = "Rex Terry"
                        },
                        new
                        {
                            Id = 61,
                            Balance = 2662.705491379475167m,
                            Email = "Laney.Hudson56@gmail.com",
                            FullName = "Loraine Langosh"
                        },
                        new
                        {
                            Id = 79,
                            Balance = 4194.451569557444689m,
                            Email = "Frederick.King5@yahoo.com",
                            FullName = "Rosemary Gleichner"
                        },
                        new
                        {
                            Id = 88,
                            Balance = 8961.512142489348232m,
                            Email = "Vallie35@gmail.com",
                            FullName = "Jared Quitzon"
                        },
                        new
                        {
                            Id = 90,
                            Balance = 7666.2586012606219m,
                            Email = "Demarco60@gmail.com",
                            FullName = "Dewayne O'Conner"
                        },
                        new
                        {
                            Id = 51,
                            Email = "Hope_Walsh@gmail.com",
                            FullName = "Rowan Nienow"
                        },
                        new
                        {
                            Id = 31,
                            Balance = 8831.631371574747295m,
                            Email = "Rae.Schmidt36@hotmail.com",
                            FullName = "Carmelo Collier"
                        },
                        new
                        {
                            Id = 78,
                            Email = "Lavon.Ernser98@hotmail.com",
                            FullName = "Iliana Rosenbaum"
                        },
                        new
                        {
                            Id = 28,
                            Balance = 2774.125864401087844m,
                            Email = "Rosemary_Funk32@hotmail.com",
                            FullName = "Buck Davis"
                        },
                        new
                        {
                            Id = 2,
                            Email = "Amie_Stokes52@hotmail.com",
                            FullName = "Shemar Parisian"
                        },
                        new
                        {
                            Id = 63,
                            Email = "Abigayle3@yahoo.com",
                            FullName = "Johnpaul Lockman"
                        },
                        new
                        {
                            Id = 92,
                            Balance = 4201.422402685346596m,
                            Email = "Gerardo_Hauck@gmail.com",
                            FullName = "Gennaro Lowe"
                        },
                        new
                        {
                            Id = 97,
                            Email = "Felix.Dicki28@gmail.com",
                            FullName = "Stephany Langosh"
                        },
                        new
                        {
                            Id = 80,
                            Balance = 3785.102143977636316m,
                            Email = "Macey72@hotmail.com",
                            FullName = "Phoebe Paucek"
                        },
                        new
                        {
                            Id = 98,
                            Email = "Lillie.Streich36@gmail.com",
                            FullName = "Freddy Leuschke"
                        },
                        new
                        {
                            Id = 34,
                            Balance = 2087.61954269434831m,
                            Email = "Jamaal.Roberts@gmail.com",
                            FullName = "Emie McGlynn"
                        },
                        new
                        {
                            Id = 93,
                            Balance = 7183.36254274911658m,
                            Email = "Lucinda29@gmail.com",
                            FullName = "Amely Pollich"
                        },
                        new
                        {
                            Id = 26,
                            Email = "Trever66@hotmail.com",
                            FullName = "Tessie Moore"
                        },
                        new
                        {
                            Id = 15,
                            Email = "Clovis_Treutel@hotmail.com",
                            FullName = "Allan Pouros"
                        },
                        new
                        {
                            Id = 39,
                            Email = "Eloise.Kassulke65@hotmail.com",
                            FullName = "Jazlyn Wehner"
                        },
                        new
                        {
                            Id = 9,
                            Email = "Waino_Erdman98@gmail.com",
                            FullName = "Libbie Hettinger"
                        },
                        new
                        {
                            Id = 12,
                            Balance = 6968.315359778550535m,
                            Email = "Alberta_Wiza37@gmail.com",
                            FullName = "Victoria Carroll"
                        },
                        new
                        {
                            Id = 52,
                            Email = "Andreane65@hotmail.com",
                            FullName = "Kiarra Balistreri"
                        },
                        new
                        {
                            Id = 38,
                            Email = "Arthur_Bauch@hotmail.com",
                            FullName = "Eleonore Leuschke"
                        },
                        new
                        {
                            Id = 83,
                            Balance = 6692.686956969711103m,
                            Email = "Alexis.Cassin@yahoo.com",
                            FullName = "Annetta Boyle"
                        },
                        new
                        {
                            Id = 24,
                            Email = "Ericka43@gmail.com",
                            FullName = "Alene Daugherty"
                        },
                        new
                        {
                            Id = 21,
                            Balance = 1482.974880344884585m,
                            Email = "Jovani.Lynch21@yahoo.com",
                            FullName = "Ressie Dicki"
                        },
                        new
                        {
                            Id = 16,
                            Email = "June.Reilly69@gmail.com",
                            FullName = "Johan Cremin"
                        },
                        new
                        {
                            Id = 74,
                            Balance = 4224.72787556814028m,
                            Email = "Yasmin7@gmail.com",
                            FullName = "Kaelyn Strosin"
                        },
                        new
                        {
                            Id = 95,
                            Balance = 4900.873651525270594m,
                            Email = "Delphia.Heidenreich@hotmail.com",
                            FullName = "Marisa Kreiger"
                        },
                        new
                        {
                            Id = 40,
                            Balance = 8247.827197297070668m,
                            Email = "Donald.Schamberger22@gmail.com",
                            FullName = "Russell Dooley"
                        },
                        new
                        {
                            Id = 20,
                            Balance = 3892.958252145770554m,
                            Email = "Gerda_Thompson@hotmail.com",
                            FullName = "Ivah Reilly"
                        },
                        new
                        {
                            Id = 71,
                            Email = "Woodrow_Lockman@gmail.com",
                            FullName = "Carmine DuBuque"
                        },
                        new
                        {
                            Id = 14,
                            Email = "Ella_Langworth@gmail.com",
                            FullName = "Tomasa Ernser"
                        },
                        new
                        {
                            Id = 77,
                            Balance = 2296.539651446313085m,
                            Email = "Doyle_Larkin@gmail.com",
                            FullName = "Antoinette Zboncak"
                        },
                        new
                        {
                            Id = 81,
                            Email = "Kianna_Zulauf44@gmail.com",
                            FullName = "Melisa Dach"
                        },
                        new
                        {
                            Id = 1,
                            Balance = 2658.346107252376078m,
                            Email = "Milo.Morar@hotmail.com",
                            FullName = "Aaron Graham"
                        },
                        new
                        {
                            Id = 82,
                            Email = "Lera_Olson@hotmail.com",
                            FullName = "Dexter Schaefer"
                        },
                        new
                        {
                            Id = 73,
                            Email = "Meda23@hotmail.com",
                            FullName = "Eliezer Cummings"
                        },
                        new
                        {
                            Id = 70,
                            Email = "Heath46@gmail.com",
                            FullName = "Edgar Volkman"
                        },
                        new
                        {
                            Id = 54,
                            Email = "Kaleigh.Wiza85@hotmail.com",
                            FullName = "Madison Murphy"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
