// <auto-generated />
using System;
using Beer2beer.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Beer2beer.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240217165901_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("Beer2beer.Core.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Balance")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EntryDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 30,
                            Balance = 9284.375511752555323m,
                            Email = "Domenick5@yahoo.com",
                            FullName = "Arlie Kessler"
                        },
                        new
                        {
                            Id = 25,
                            Balance = 9220.765783472084269m,
                            Email = "Danyka20@gmail.com",
                            FullName = "Pablo Treutel"
                        },
                        new
                        {
                            Id = 57,
                            Balance = 1661.579683383884032m,
                            Email = "Drew_Aufderhar91@yahoo.com",
                            FullName = "Helene Kub"
                        },
                        new
                        {
                            Id = 61,
                            Email = "Teagan13@gmail.com",
                            FullName = "Hazel Pouros"
                        },
                        new
                        {
                            Id = 43,
                            Balance = 5249.640449530623277m,
                            Email = "Retta.Gislason@hotmail.com",
                            FullName = "Turner Daniel"
                        },
                        new
                        {
                            Id = 44,
                            Balance = 3278.600496286258483m,
                            Email = "Bernice.Bosco46@hotmail.com",
                            FullName = "Delta Farrell"
                        },
                        new
                        {
                            Id = 22,
                            Email = "Sigrid99@gmail.com",
                            FullName = "Daija Lakin"
                        },
                        new
                        {
                            Id = 8,
                            Email = "Clement.Hauck83@yahoo.com",
                            FullName = "Icie Considine"
                        },
                        new
                        {
                            Id = 70,
                            Email = "Irwin66@gmail.com",
                            FullName = "Claudia Parisian"
                        },
                        new
                        {
                            Id = 17,
                            Email = "Dejon_Stiedemann17@gmail.com",
                            FullName = "Sigrid Maggio"
                        },
                        new
                        {
                            Id = 13,
                            Balance = 3026.788889546890324m,
                            Email = "Jedidiah.Cruickshank47@hotmail.com",
                            FullName = "Vince Schmidt"
                        },
                        new
                        {
                            Id = 67,
                            Balance = 2693.212059945012418m,
                            Email = "Xzavier_Wunsch86@hotmail.com",
                            FullName = "Kenya Collins"
                        },
                        new
                        {
                            Id = 95,
                            Balance = 692.5782271995871219m,
                            Email = "Andy_Baumbach@hotmail.com",
                            FullName = "Michele Mann"
                        },
                        new
                        {
                            Id = 68,
                            Balance = 6527.761797955019104m,
                            Email = "Lewis.Pacocha43@gmail.com",
                            FullName = "Ray Brekke"
                        },
                        new
                        {
                            Id = 34,
                            Email = "Ceasar.Kiehn@gmail.com",
                            FullName = "Rosalinda McClure"
                        },
                        new
                        {
                            Id = 77,
                            Balance = 1439.776564817473684m,
                            Email = "Loren_Zulauf68@gmail.com",
                            FullName = "Dasia Johnston"
                        },
                        new
                        {
                            Id = 7,
                            Balance = 5993.53897302381475m,
                            Email = "Annette.Conn@hotmail.com",
                            FullName = "Isobel Reichert"
                        },
                        new
                        {
                            Id = 83,
                            Email = "Kira_Borer@yahoo.com",
                            FullName = "London Predovic"
                        },
                        new
                        {
                            Id = 24,
                            Balance = 3815.004489076743049m,
                            Email = "Stephanie_Greenfelder@hotmail.com",
                            FullName = "Clint Emmerich"
                        },
                        new
                        {
                            Id = 78,
                            Email = "Ervin2@hotmail.com",
                            FullName = "Jaime Kutch"
                        },
                        new
                        {
                            Id = 32,
                            Balance = 8948.884534753300543m,
                            Email = "Teresa_Kulas28@hotmail.com",
                            FullName = "Skye Buckridge"
                        },
                        new
                        {
                            Id = 36,
                            Email = "Mara80@gmail.com",
                            FullName = "Tyrique Grant"
                        },
                        new
                        {
                            Id = 5,
                            Email = "Demarco_Gleason@gmail.com",
                            FullName = "Llewellyn Walsh"
                        },
                        new
                        {
                            Id = 91,
                            Balance = 9346.506117384203965m,
                            Email = "Donavon.Lindgren78@yahoo.com",
                            FullName = "Romaine Waters"
                        },
                        new
                        {
                            Id = 29,
                            Balance = 1277.599184902921132m,
                            Email = "Lilyan28@hotmail.com",
                            FullName = "Kathleen Legros"
                        },
                        new
                        {
                            Id = 51,
                            Email = "Maybelle.Schneider@hotmail.com",
                            FullName = "Samara Rodriguez"
                        },
                        new
                        {
                            Id = 28,
                            Balance = 9276.087755858430583m,
                            Email = "Lisette59@hotmail.com",
                            FullName = "Richie Adams"
                        },
                        new
                        {
                            Id = 74,
                            Balance = 3341.140156740263932m,
                            Email = "Nathanial.Wiza35@yahoo.com",
                            FullName = "Jaime Feeney"
                        },
                        new
                        {
                            Id = 97,
                            Email = "Natasha.Durgan@yahoo.com",
                            FullName = "Austin McCullough"
                        },
                        new
                        {
                            Id = 10,
                            Email = "Brown2@yahoo.com",
                            FullName = "Geoffrey Jaskolski"
                        },
                        new
                        {
                            Id = 27,
                            Email = "Pasquale_McLaughlin90@hotmail.com",
                            FullName = "Golden Ondricka"
                        },
                        new
                        {
                            Id = 14,
                            Balance = 539.1394957260602434m,
                            Email = "Nellie36@hotmail.com",
                            FullName = "Bernhard Luettgen"
                        },
                        new
                        {
                            Id = 54,
                            Balance = 4063.904398441438561m,
                            Email = "Bulah.Goyette0@gmail.com",
                            FullName = "Mikel Ryan"
                        },
                        new
                        {
                            Id = 71,
                            Balance = 4743.059600446646797m,
                            Email = "Ella.Stoltenberg@yahoo.com",
                            FullName = "Winston Konopelski"
                        },
                        new
                        {
                            Id = 16,
                            Email = "Earl_Marvin@gmail.com",
                            FullName = "Flo Cassin"
                        },
                        new
                        {
                            Id = 19,
                            Balance = 8203.518238216032676m,
                            Email = "Noemi_Weber26@gmail.com",
                            FullName = "Barrett Considine"
                        },
                        new
                        {
                            Id = 1,
                            Email = "Yolanda.Prosacco86@gmail.com",
                            FullName = "Marcus Durgan"
                        },
                        new
                        {
                            Id = 65,
                            Balance = 6100.65731445998059m,
                            Email = "Katlynn_Windler@gmail.com",
                            FullName = "Jeanette Abernathy"
                        },
                        new
                        {
                            Id = 47,
                            Email = "Crystel_Rutherford@gmail.com",
                            FullName = "Adelbert Aufderhar"
                        },
                        new
                        {
                            Id = 49,
                            Email = "Valentina_Parker@yahoo.com",
                            FullName = "Daphnee Hahn"
                        },
                        new
                        {
                            Id = 40,
                            Balance = 4446.573400114418539m,
                            Email = "Marion58@gmail.com",
                            FullName = "Luz Kshlerin"
                        },
                        new
                        {
                            Id = 80,
                            Email = "Vincenza48@yahoo.com",
                            FullName = "Zakary Oberbrunner"
                        },
                        new
                        {
                            Id = 33,
                            Email = "Hudson.Hyatt@hotmail.com",
                            FullName = "Lyric Bergstrom"
                        },
                        new
                        {
                            Id = 88,
                            Balance = 3837.00160971127639m,
                            Email = "Ena_Hudson@hotmail.com",
                            FullName = "Nellie Stark"
                        },
                        new
                        {
                            Id = 60,
                            Email = "Myrna.Zulauf97@hotmail.com",
                            FullName = "Clementine Dooley"
                        },
                        new
                        {
                            Id = 87,
                            Email = "Hanna.Blanda87@yahoo.com",
                            FullName = "Shane Braun"
                        },
                        new
                        {
                            Id = 73,
                            Email = "Jessika31@yahoo.com",
                            FullName = "Porter Simonis"
                        },
                        new
                        {
                            Id = 42,
                            Email = "Alessandro.Dach0@yahoo.com",
                            FullName = "Aliya Cremin"
                        },
                        new
                        {
                            Id = 89,
                            Balance = 6450.357932325058168m,
                            Email = "Caroline.Sanford@yahoo.com",
                            FullName = "Alia Romaguera"
                        },
                        new
                        {
                            Id = 84,
                            Email = "Sven.Pfannerstill90@hotmail.com",
                            FullName = "Willow Farrell"
                        },
                        new
                        {
                            Id = 81,
                            Balance = 9888.524356646483272m,
                            Email = "Talon15@yahoo.com",
                            FullName = "Carmine Carter"
                        },
                        new
                        {
                            Id = 96,
                            Email = "Celia.Dickinson@gmail.com",
                            FullName = "Federico Beier"
                        },
                        new
                        {
                            Id = 69,
                            Balance = 2160.381658335360283m,
                            Email = "Etha_Kshlerin58@gmail.com",
                            FullName = "Madyson Kautzer"
                        },
                        new
                        {
                            Id = 93,
                            Balance = 6639.472867481464042m,
                            Email = "Gus_Harris35@gmail.com",
                            FullName = "Reva Mayer"
                        },
                        new
                        {
                            Id = 98,
                            Balance = 4048.308125348146219m,
                            Email = "Kirsten_Sanford@hotmail.com",
                            FullName = "Haylie Leuschke"
                        },
                        new
                        {
                            Id = 4,
                            Email = "Graciela35@yahoo.com",
                            FullName = "Gregory Fritsch"
                        },
                        new
                        {
                            Id = 72,
                            Balance = 849.0507126994957879m,
                            Email = "Ethel.Stracke@yahoo.com",
                            FullName = "Eladio Jones"
                        },
                        new
                        {
                            Id = 11,
                            Balance = 1487.976711079677796m,
                            Email = "Mario.Hamill@gmail.com",
                            FullName = "Gus Olson"
                        },
                        new
                        {
                            Id = 56,
                            Email = "Madonna_Romaguera91@yahoo.com",
                            FullName = "Frederik Yundt"
                        },
                        new
                        {
                            Id = 38,
                            Balance = 5157.890491227794902m,
                            Email = "Marc.Murphy@hotmail.com",
                            FullName = "Edyth Konopelski"
                        },
                        new
                        {
                            Id = 53,
                            Balance = 6859.503308821285594m,
                            Email = "Rolando.Kovacek15@gmail.com",
                            FullName = "Fredrick Kutch"
                        },
                        new
                        {
                            Id = 64,
                            Email = "Itzel4@yahoo.com",
                            FullName = "Amber Lemke"
                        },
                        new
                        {
                            Id = 46,
                            Email = "Adolfo45@hotmail.com",
                            FullName = "Tomas Schumm"
                        },
                        new
                        {
                            Id = 58,
                            Email = "Sarina.Daugherty60@yahoo.com",
                            FullName = "Calista Hudson"
                        },
                        new
                        {
                            Id = 75,
                            Balance = 4222.745809851554578m,
                            Email = "Jacques.Upton11@gmail.com",
                            FullName = "Jerrold Hintz"
                        },
                        new
                        {
                            Id = 21,
                            Balance = 992.4170413170433663m,
                            Email = "Icie.Schumm53@gmail.com",
                            FullName = "Karianne Durgan"
                        },
                        new
                        {
                            Id = 90,
                            Balance = 1658.233022844377935m,
                            Email = "Wellington71@yahoo.com",
                            FullName = "Oma Reilly"
                        },
                        new
                        {
                            Id = 39,
                            Email = "Felix.Ledner@gmail.com",
                            FullName = "Elissa Morar"
                        },
                        new
                        {
                            Id = 55,
                            Balance = 4720.853150983939771m,
                            Email = "Ada.Konopelski@hotmail.com",
                            FullName = "Rafael Ankunding"
                        },
                        new
                        {
                            Id = 31,
                            Balance = 5682.877687741686508m,
                            Email = "Valentin_McClure36@hotmail.com",
                            FullName = "Candido Brown"
                        },
                        new
                        {
                            Id = 50,
                            Balance = 9620.831989452464065m,
                            Email = "Cecil.Mueller@yahoo.com",
                            FullName = "Stefanie Stracke"
                        },
                        new
                        {
                            Id = 85,
                            Balance = 9268.426068530697892m,
                            Email = "Haleigh_Yundt67@gmail.com",
                            FullName = "Aubree Haag"
                        },
                        new
                        {
                            Id = 63,
                            Email = "Rodrigo3@yahoo.com",
                            FullName = "Anya Halvorson"
                        },
                        new
                        {
                            Id = 23,
                            Email = "Aurelia.Heathcote33@yahoo.com",
                            FullName = "Piper Prohaska"
                        },
                        new
                        {
                            Id = 12,
                            Email = "Savanah.Schinner@hotmail.com",
                            FullName = "Brandon Cassin"
                        },
                        new
                        {
                            Id = 99,
                            Balance = 2045.353943300905918m,
                            Email = "Nathanial4@gmail.com",
                            FullName = "Harold Lindgren"
                        },
                        new
                        {
                            Id = 52,
                            Email = "Kiara.Ruecker@yahoo.com",
                            FullName = "Erling Ernser"
                        },
                        new
                        {
                            Id = 92,
                            Balance = 9329.583201885969868m,
                            Email = "Keaton82@hotmail.com",
                            FullName = "Cyril Mayer"
                        },
                        new
                        {
                            Id = 26,
                            Email = "Narciso82@hotmail.com",
                            FullName = "Mark Strosin"
                        },
                        new
                        {
                            Id = 41,
                            Email = "Darius10@yahoo.com",
                            FullName = "Mafalda McClure"
                        },
                        new
                        {
                            Id = 20,
                            Email = "Myrtie_Schoen@hotmail.com",
                            FullName = "Virginie Halvorson"
                        },
                        new
                        {
                            Id = 6,
                            Email = "Kylee_Cronin@gmail.com",
                            FullName = "Ernestina Berge"
                        },
                        new
                        {
                            Id = 9,
                            Balance = 7755.466163640989023m,
                            Email = "Dangelo.Reichert@yahoo.com",
                            FullName = "Lorena O'Hara"
                        },
                        new
                        {
                            Id = 62,
                            Balance = 4262.610675717429463m,
                            Email = "Edwina.Padberg@yahoo.com",
                            FullName = "Reba Hoeger"
                        },
                        new
                        {
                            Id = 45,
                            Balance = 6933.719154383566687m,
                            Email = "Dasia.Boyle24@gmail.com",
                            FullName = "Vinnie Ward"
                        },
                        new
                        {
                            Id = 59,
                            Balance = 5477.378830178176954m,
                            Email = "Taurean_Doyle@hotmail.com",
                            FullName = "Jermain Kuhic"
                        },
                        new
                        {
                            Id = 2,
                            Balance = 5611.116408160329208m,
                            Email = "Kenton.Goodwin@yahoo.com",
                            FullName = "Felicity Weissnat"
                        },
                        new
                        {
                            Id = 76,
                            Email = "Electa36@gmail.com",
                            FullName = "Efren Morar"
                        },
                        new
                        {
                            Id = 15,
                            Email = "Cassie.Johnston@gmail.com",
                            FullName = "Halle Veum"
                        },
                        new
                        {
                            Id = 48,
                            Balance = 7980.198994229857075m,
                            Email = "Tillman42@gmail.com",
                            FullName = "Deondre Reichert"
                        },
                        new
                        {
                            Id = 79,
                            Email = "Adan.Mante96@yahoo.com",
                            FullName = "Rosendo Graham"
                        },
                        new
                        {
                            Id = 100,
                            Balance = 2735.911085498064154m,
                            Email = "Selmer0@gmail.com",
                            FullName = "Elwyn Gibson"
                        },
                        new
                        {
                            Id = 94,
                            Balance = 923.1313296651359662m,
                            Email = "Bianka_Reynolds@gmail.com",
                            FullName = "Ariane Borer"
                        },
                        new
                        {
                            Id = 18,
                            Balance = 7924.842370551266533m,
                            Email = "Estella_Mosciski@yahoo.com",
                            FullName = "Myrtle Rau"
                        },
                        new
                        {
                            Id = 35,
                            Email = "Emil.Bode@hotmail.com",
                            FullName = "Cristina Conroy"
                        },
                        new
                        {
                            Id = 86,
                            Balance = 4618.44236224613386m,
                            Email = "Percy_Leffler@hotmail.com",
                            FullName = "Etha Lebsack"
                        },
                        new
                        {
                            Id = 3,
                            Email = "Hobart.Muller@yahoo.com",
                            FullName = "Jeanie Bayer"
                        },
                        new
                        {
                            Id = 66,
                            Email = "Shirley.Quitzon62@hotmail.com",
                            FullName = "Marion Boyle"
                        },
                        new
                        {
                            Id = 82,
                            Email = "Kelley.Hettinger94@hotmail.com",
                            FullName = "Maximilian Block"
                        },
                        new
                        {
                            Id = 37,
                            Balance = 8634.771846351751726m,
                            Email = "Durward87@hotmail.com",
                            FullName = "Billy Tremblay"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
